list = list(map(int, input().split()))
highest = max(list)
lowest = min(list)
average = sum(list) / len(list)
print(f"Highest Temperature: {highest}", end=" ")
print(f"Lowest Temperature: {lowest}", end=" ")
print(f"Average Temperature: {average:.2f}", end=" ")
list.sort()
print(f"Ascending Order: {list}", end=" ")
list.reverse()
print(f"Descending Order: {list}", end=" ")
